export const TODO_CREATE_REQUESTED = 'TODO_CREATE_REQUESTED'
export const TODO_CREATE_SUCCEEDED = 'TODO_CREATE_SUCCEEDED'
export const TODO_CREATE_FAILED = 'TODO_CREATE_FAILED'

export const TODOS_GET_REQUESTED = 'TODOS_GET_REQUESTED'
export const TODOS_GET_SUCCEEDED = 'TODOS_GET_SUCCEEDED'
export const TODOS_GET_FAILED = 'TODOS_GETFAILED'

export const TODO_UPDATE_REQUESTED = 'TODO_UPDATE_REQUESTED'
export const TODO_UPDATE_SUCCEEDED = 'TODO_UPDATE_SUCCEEDED'
export const TODO_UPDATE_FAILED = 'TODO_UPDATE_FAILED'

export const TODO_DELETE_REQUESTED = 'TODO_DELETE_REQUESTED'
export const TODO_DELETE_SUCCEEDED = 'TODO_DELETE_SUCCEEDED'
export const TODO_DELETE_FAILED = 'TODO_DELETE_FAILED'
